# app/config.py
import os
import secrets
from pydantic import AliasChoices, Field
from pydantic_settings import BaseSettings
from pydantic_settings import SettingsConfigDict

class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="allow")

    # Process Bindings
    HOST: str = "127.0.0.1"
    PORT: int = int(os.getenv("PORT", 8080))

    # Deployment Modes
    # 'local' means managed locally by Electron. 'remote' means cloud-hosted (Render).
    DEPLOYMENT_MODE: str = os.getenv("DEPLOYMENT_MODE", "local")

    # Token Authentication
    # Ephemeral token generated by Electron on startup (for local) or persistent env variable (for remote)
    AUTH_TOKEN: str = Field(
        default="",
        validation_alias=AliasChoices("WEB_INTELLIGENCE_AUTH_TOKEN", "AUTH_TOKEN")
    )

    # Storage and Durable Queuing
    # 'local' (in-memory/SQLite) vs. 'redis' (production queues on Render)
    STORAGE_BACKEND: str = os.getenv("STORAGE_BACKEND", "local")
    REDIS_URL: str = os.getenv("REDIS_URL", "")
    # Concurrency and Budgets
    MAX_CONCURRENT_OPS: int = int(os.getenv("MAX_CONCURRENT_OPS", 3))
    MAX_MEMORY_MB: int = int(os.getenv("MAX_MEMORY_MB", 512))
    DAILY_SPEND_LIMIT_USD: float = float(os.getenv("DAILY_SPEND_LIMIT_USD", 50.0))

    # CORS policies
    # Disabled by default in remote mode unless explicitly authorized
    CORS_ORIGINS: str = os.getenv("CORS_ORIGINS", "")
    ALLOW_UNAUTHENTICATED_DOCS: bool = os.getenv("ALLOW_UNAUTHENTICATED_DOCS", "").lower() in ("1", "true", "yes")

settings = Settings()

# Secure fallback token generation if not provided in local mode
if settings.DEPLOYMENT_MODE == "local" and not settings.AUTH_TOKEN:
    settings.AUTH_TOKEN = secrets.token_hex(32)

def auth_is_configured() -> bool:
    return bool(settings.AUTH_TOKEN)

def raw_header_credentials_allowed() -> bool:
    return settings.DEPLOYMENT_MODE == "local"

def unauthenticated_docs_allowed() -> bool:
    return settings.DEPLOYMENT_MODE == "local" and settings.ALLOW_UNAUTHENTICATED_DOCS
