# app/config.py
import os
import secrets
import logging
from pydantic import AliasChoices, Field, model_validator
from pydantic_settings import BaseSettings
from pydantic_settings import SettingsConfigDict

class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="allow")

    # Process Bindings
    HOST: str = "127.0.0.1"
    PORT: int = int(os.getenv("PORT", 8080))

    # Deployment Modes
    # 'local' means managed locally by Electron. 'remote' means cloud-hosted (Render).
    DEPLOYMENT_MODE: str = os.getenv("DEPLOYMENT_MODE", "local")

    # Token Authentication
    # Ephemeral token generated by Electron on startup (for local) or persistent env variable (for remote)
    AUTH_TOKEN: str = Field(
        default="",
        validation_alias=AliasChoices("WEB_INTELLIGENCE_AUTH_TOKEN", "AUTH_TOKEN")
    )

    # Storage and Durable Queuing
    # 'local' (in-memory/SQLite) vs. 'redis' (production queues on Render)
    STORAGE_BACKEND: str = os.getenv("STORAGE_BACKEND", "local")
    REDIS_URL: str = os.getenv("REDIS_URL", "")
    # Concurrency and Budgets
    MAX_CONCURRENT_OPS: int = int(os.getenv("MAX_CONCURRENT_OPS", 3))
    MAX_MEMORY_MB: int = int(os.getenv("MAX_MEMORY_MB", 512))
    DAILY_SPEND_LIMIT_USD: float = float(os.getenv("DAILY_SPEND_LIMIT_USD", 50.0))
    # Conservative per-operation budget reserved at admission, before the real
    # cost is known. Reservation makes the daily ceiling atomic across
    # replicas; it is released and reconciled to the observed cost on
    # completion, or released outright on cancel/failure.
    DEFAULT_OPERATION_COST_RESERVE_USD: float = float(
        os.getenv("DEFAULT_OPERATION_COST_RESERVE_USD", 0.25)
    )

    # Durability
    # When redis storage is selected but the backend is unreachable, refuse to
    # start (fail closed) instead of silently falling back to process-local
    # memory. Set false only for explicitly disposable deployments.
    REDIS_REQUIRED: bool = os.getenv("REDIS_REQUIRED", "").lower() in ("1", "true", "yes")
    # Lease TTL for concurrency slots and operation liveness (seconds).
    CONCURRENCY_LEASE_TTL_SECONDS: int = int(os.getenv("CONCURRENCY_LEASE_TTL_SECONDS", 3600))
    # How often a running service re-runs the stale-operation reconciliation
    # scan. Must be shorter than CONCURRENCY_LEASE_TTL_SECONDS so an operation
    # orphaned by a crash is eventually failed rather than stuck forever.
    STALE_RECONCILE_INTERVAL_SECONDS: int = int(os.getenv("STALE_RECONCILE_INTERVAL_SECONDS", 60))

    @model_validator(mode="after")
    def _validate_operational_limits(self):
        # These settings gate leases and reconciliation loops; non-positive
        # values would make Redis SET ... EX fail or create a tight scan loop.
        if self.CONCURRENCY_LEASE_TTL_SECONDS <= 0:
            raise ValueError("CONCURRENCY_LEASE_TTL_SECONDS must be a positive integer.")
        if self.STALE_RECONCILE_INTERVAL_SECONDS <= 0:
            raise ValueError("STALE_RECONCILE_INTERVAL_SECONDS must be a positive integer.")
        if self.DAILY_SPEND_LIMIT_USD <= 0:
            raise ValueError("DAILY_SPEND_LIMIT_USD must be positive.")
        if self.DEFAULT_OPERATION_COST_RESERVE_USD <= 0:
            # A zero reserve would make every admission reservation a no-op, so
            # concurrent operations would bypass the daily ceiling entirely.
            raise ValueError("DEFAULT_OPERATION_COST_RESERVE_USD must be positive.")
        if (
            self.DEFAULT_OPERATION_COST_RESERVE_USD > self.DAILY_SPEND_LIMIT_USD
            and "DEFAULT_OPERATION_COST_RESERVE_USD" not in self.model_fields_set
        ):
            # The documented default reserve exceeds the configured ceiling, so
            # every operator-facing request without a smaller explicit
            # maximumModelCostUsd would be rejected. Fail clearly at startup
            # (only when the reserve was left at its default) instead of
            # appearing healthy while refusing all normal work.
            raise ValueError(
                "DEFAULT_OPERATION_COST_RESERVE_USD exceeds DAILY_SPEND_LIMIT_USD; "
                "increase the daily limit or lower the per-operation reserve."
            )
        return self

    # Local input ingestion
    # Explicit filesystem roots that local document/repository inputs may be
    # read from (os.pathsep-separated). Empty disables local file inputs.
    LOCAL_INPUT_ROOTS: str = os.getenv("LOCAL_INPUT_ROOTS", "")

    # CORS policies
    # Disabled by default in remote mode unless explicitly authorized
    CORS_ORIGINS: str = os.getenv("CORS_ORIGINS", "")
    ALLOW_UNAUTHENTICATED_DOCS: bool = os.getenv("ALLOW_UNAUTHENTICATED_DOCS", "").lower() in ("1", "true", "yes")

    # Optional Brain Memory integration. The complete credential group is required
    # before either recall or outcome ingestion can run.
    BRAIN_MEMORY_ENABLED: bool = False
    BRAIN_MEMORY_CONTEXT_ENABLED: bool = False
    BRAIN_MEMORY_URL: str = ""
    BRAIN_MEMORY_KEY_ID: str = ""
    BRAIN_MEMORY_SECRET: str = ""

settings = Settings()

_logger = logging.getLogger("web-intelligence")

# Secure fallback token generation if not provided in local mode
if settings.DEPLOYMENT_MODE == "local" and not settings.AUTH_TOKEN:
    settings.AUTH_TOKEN = secrets.token_hex(32)

def auth_is_configured() -> bool:
    return bool(settings.AUTH_TOKEN)

def raw_header_credentials_allowed() -> bool:
    return settings.DEPLOYMENT_MODE == "local"

def unauthenticated_docs_allowed() -> bool:
    return settings.DEPLOYMENT_MODE == "local" and settings.ALLOW_UNAUTHENTICATED_DOCS


def brain_memory_client():
    """Return the optional Brain client only for a complete, explicit config."""
    if not settings.BRAIN_MEMORY_ENABLED:
        return None
    values = {
        "BRAIN_MEMORY_URL": settings.BRAIN_MEMORY_URL.strip(),
        "BRAIN_MEMORY_KEY_ID": settings.BRAIN_MEMORY_KEY_ID.strip(),
        "BRAIN_MEMORY_SECRET": settings.BRAIN_MEMORY_SECRET.strip(),
    }
    missing = [name for name, value in values.items() if not value]
    if missing:
        _logger.warning("Brain Memory disabled because its credential group is incomplete: %s", ", ".join(missing))
        return None
    try:
        from app.brain_memory import BrainMemoryClient
        return BrainMemoryClient(values["BRAIN_MEMORY_URL"], values["BRAIN_MEMORY_KEY_ID"], values["BRAIN_MEMORY_SECRET"])
    except ValueError:
        _logger.warning("Brain Memory disabled because its URL is invalid", exc_info=True)
        return None
