# app/config.py
import os
import ipaddress
import secrets
import logging
from dataclasses import dataclass
from urllib.parse import urlsplit
from pydantic import AliasChoices, Field, model_validator
from pydantic_settings import BaseSettings
from pydantic_settings import SettingsConfigDict

# Minimum ownership-lease TTL. The heartbeat renews once per second, so a lease
# must comfortably exceed that cadence to survive normal scheduling/network
# jitter without being treated as lost.
MIN_CONCURRENCY_LEASE_TTL_SECONDS = 30


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="allow")

    # Process Bindings
    HOST: str = "127.0.0.1"
    PORT: int = int(os.getenv("PORT", 8080))

    # Deployment Modes
    # 'local' means managed locally by Electron. 'remote' means cloud-hosted (primary:
    # Azure Container Apps, see grafana_observability.py's CONTAINER_APP_NAME check and
    # the deploy job in .github/workflows/sidecar-tests.yml; legacy/secondary: Render).
    DEPLOYMENT_MODE: str = os.getenv("DEPLOYMENT_MODE", "local")

    # Token Authentication
    # Ephemeral token generated by Electron on startup (for local) or persistent env variable (for remote)
    AUTH_TOKEN: str = Field(
        default="",
        validation_alias=AliasChoices("WEB_INTELLIGENCE_AUTH_TOKEN", "AUTH_TOKEN")
    )

    # Storage and Durable Queuing
    # 'local' (in-memory/SQLite) vs. 'redis' (production queues; primary deployment is
    # Azure Container Apps, with a legacy Render instance still running the same way)
    STORAGE_BACKEND: str = os.getenv("STORAGE_BACKEND", "local")
    REDIS_URL: str = os.getenv("REDIS_URL", "")
    # Concurrency and resource limits. The daily spend ceiling below is a local
    # guard: it is enforced only for externally-metered work this service itself
    # cannot delegate. When AI-OpenRouter serves the request it is the budget
    # authority, and local models have no external cost, so admission neither
    # reserves nor reconciles spend for those paths.
    MAX_CONCURRENT_OPS: int = int(os.getenv("MAX_CONCURRENT_OPS", 3))
    MAX_MEMORY_MB: int = int(os.getenv("MAX_MEMORY_MB", 512))
    DAILY_SPEND_LIMIT_USD: float = float(os.getenv("DAILY_SPEND_LIMIT_USD", 50.0))
    # Conservative per-operation budget reserved at admission, before the real
    # cost is known. Reservation makes the daily ceiling atomic across
    # replicas; it is released and reconciled to the observed cost on
    # completion, or released outright on cancel/failure.
    DEFAULT_OPERATION_COST_RESERVE_USD: float = float(
        os.getenv("DEFAULT_OPERATION_COST_RESERVE_USD", 0.25)
    )

    # Durability
    # When redis storage is selected but the backend is unreachable, refuse to
    # start (fail closed) instead of silently falling back to process-local
    # memory. Set false only for explicitly disposable deployments.
    REDIS_REQUIRED: bool = os.getenv("REDIS_REQUIRED", "").lower() in ("1", "true", "yes")
    # Lease TTL for concurrency slots and operation liveness (seconds).
    CONCURRENCY_LEASE_TTL_SECONDS: int = int(os.getenv("CONCURRENCY_LEASE_TTL_SECONDS", 3600))
    # How often a running service re-runs the stale-operation reconciliation
    # scan. Must be shorter than CONCURRENCY_LEASE_TTL_SECONDS so an operation
    # orphaned by a crash is eventually failed rather than stuck forever.
    STALE_RECONCILE_INTERVAL_SECONDS: int = int(os.getenv("STALE_RECONCILE_INTERVAL_SECONDS", 60))

    @model_validator(mode="after")
    def _validate_operational_limits(self):
        # These settings gate leases and reconciliation loops; non-positive
        # values would make Redis SET ... EX fail or create a tight scan loop.
        if self.CONCURRENCY_LEASE_TTL_SECONDS < MIN_CONCURRENCY_LEASE_TTL_SECONDS:
            # The ownership heartbeat runs on a fixed one-second cadence, so a
            # lease shorter than this margin expires between heartbeats and
            # aborts healthy operations as lease-lost.
            raise ValueError(
                f"CONCURRENCY_LEASE_TTL_SECONDS must be at least {MIN_CONCURRENCY_LEASE_TTL_SECONDS} seconds."
            )
        if self.STALE_RECONCILE_INTERVAL_SECONDS <= 0:
            raise ValueError("STALE_RECONCILE_INTERVAL_SECONDS must be a positive integer.")
        if self.DAILY_SPEND_LIMIT_USD <= 0:
            raise ValueError("DAILY_SPEND_LIMIT_USD must be positive.")
        if self.DEFAULT_OPERATION_COST_RESERVE_USD <= 0:
            # A zero reserve would make every admission reservation a no-op, so
            # concurrent operations would bypass the daily ceiling entirely.
            raise ValueError("DEFAULT_OPERATION_COST_RESERVE_USD must be positive.")
        if self.STALE_RECONCILE_INTERVAL_SECONDS >= self.CONCURRENCY_LEASE_TTL_SECONDS:
            # The scan must run within the lease window, otherwise an operation
            # orphaned by a crash stays queued/running for longer than its lease
            # implies and blocks a concurrency slot until the next pass.
            raise ValueError(
                "STALE_RECONCILE_INTERVAL_SECONDS must be shorter than CONCURRENCY_LEASE_TTL_SECONDS."
            )
        if (
            self.DEFAULT_OPERATION_COST_RESERVE_USD > self.DAILY_SPEND_LIMIT_USD
            and "DEFAULT_OPERATION_COST_RESERVE_USD" not in self.model_fields_set
        ):
            # The documented default reserve exceeds the configured ceiling, so
            # every operator-facing request without a smaller explicit
            # maximumModelCostUsd would be rejected. Fail clearly at startup
            # (only when the reserve was left at its default) instead of
            # appearing healthy while refusing all normal work.
            raise ValueError(
                "DEFAULT_OPERATION_COST_RESERVE_USD exceeds DAILY_SPEND_LIMIT_USD; "
                "increase the daily limit or lower the per-operation reserve."
            )
        return self

    # Local input ingestion
    # Explicit filesystem roots that local document/repository inputs may be
    # read from (os.pathsep-separated). Empty disables local file inputs.
    LOCAL_INPUT_ROOTS: str = os.getenv("LOCAL_INPUT_ROOTS", "")

    # CORS policies
    # Disabled by default in remote mode unless explicitly authorized
    CORS_ORIGINS: str = os.getenv("CORS_ORIGINS", "")
    ALLOW_UNAUTHENTICATED_DOCS: bool = os.getenv("ALLOW_UNAUTHENTICATED_DOCS", "").lower() in ("1", "true", "yes")

    # Optional Brain Memory integration. The complete credential group is required
    # before either recall or outcome ingestion can run.
    BRAIN_MEMORY_ENABLED: bool = False
    BRAIN_MEMORY_CONTEXT_ENABLED: bool = False
    BRAIN_MEMORY_URL: str = ""
    BRAIN_MEMORY_KEY_ID: str = ""
    BRAIN_MEMORY_SECRET: str = ""
    AI_OPENROUTER_ENABLED: bool = False
    AI_OPENROUTER_BASE_URL: str = ""
    AI_OPENROUTER_API_KEY: str = ""
    # OpenAI-compatible model the gateway serves when a request selects no model.
    AI_OPENROUTER_DEFAULT_MODEL: str = os.getenv("AI_OPENROUTER_DEFAULT_MODEL", "gpt-4o-mini")
    # OpenAI embedding model name used when embeddings run through the gateway.
    OPENAI_EMBEDDING_MODEL: str = os.getenv("OPENAI_EMBEDDING_MODEL", "text-embedding-3-small")
    # Local model used when no gateway is configured and the request selects no
    # model. Keeps default inference local instead of an ambient external default.
    LOCAL_DEFAULT_MODEL: str = os.getenv("LOCAL_DEFAULT_MODEL", "llama3")
    # Local embedding model used for local inference. GPT Researcher's EMBEDDING
    # default is an OpenAI embedding, which would otherwise fail (or egress) when
    # credentials are masked in local mode.
    LOCAL_EMBEDDING_MODEL: str = os.getenv("LOCAL_EMBEDDING_MODEL", "nomic-embed-text")
    OLLAMA_BASE_URL: str = os.getenv("OLLAMA_BASE_URL", "http://127.0.0.1:11434")

settings = Settings()

_logger = logging.getLogger("web-intelligence")

# Secure fallback token generation if not provided in local mode
if settings.DEPLOYMENT_MODE == "local" and not settings.AUTH_TOKEN:
    settings.AUTH_TOKEN = secrets.token_hex(32)

def auth_is_configured() -> bool:
    return bool(settings.AUTH_TOKEN)

def raw_header_credentials_allowed() -> bool:
    return settings.DEPLOYMENT_MODE == "local"

def unauthenticated_docs_allowed() -> bool:
    return settings.DEPLOYMENT_MODE == "local" and settings.ALLOW_UNAUTHENTICATED_DOCS

# Providers that run locally and therefore never need external-model egress.
LOCAL_MODEL_PROVIDERS = frozenset({"ollama"})

_LOCAL_MODEL_NETWORKS = tuple(
    ipaddress.ip_network(cidr)
    for cidr in (
        "127.0.0.0/8",
        "10.0.0.0/8",
        "172.16.0.0/12",
        "192.168.0.0/16",
        "::1/128",
        "fc00::/7",
    )
)

# Credentials for external inference providers. When no gateway is configured
# these must be masked inside the request context: an ambient key combined with
# an ambient model tier would otherwise let GPT Researcher reach a provider
# directly, outside the single approved egress path.
EXTERNAL_PROVIDER_CREDENTIALS = frozenset({
    "OPENAI_API_KEY",
    "ANTHROPIC_API_KEY",
    "AZURE_OPENAI_API_KEY",
    "COHERE_API_KEY",
    "GOOGLE_API_KEY",
    "GEMINI_API_KEY",
    "FIREWORKS_API_KEY",
    "TOGETHER_API_KEY",
    "MISTRAL_API_KEY",
    "GROQ_API_KEY",
    "DASHSCOPE_API_KEY",
    "DEEPSEEK_API_KEY",
    "XAI_API_KEY",
    "OPENROUTER_API_KEY",
    "AIMLAPI_API_KEY",
    "VLLM_OPENAI_API_KEY",
    "FORGE_API_KEY",
    "MODELSLAB_API_KEY",
    "HF_TOKEN",
    "HUGGINGFACEHUB_API_TOKEN",
})

@dataclass(frozen=True)
class GatewayConfig:
    base_url: str
    api_key: str


def _validated_url_port(parsed, default: int | None = None) -> int | None:
    """Return a usable parsed port, rejecting malformed values and port zero."""
    port = parsed.port
    if port == 0:
        raise ValueError("URL port must be between 1 and 65535")
    return default if port is None else port


def external_openai_gateway_config() -> GatewayConfig | None:
    if not settings.AI_OPENROUTER_ENABLED:
        return None
    base_url = settings.AI_OPENROUTER_BASE_URL.strip().rstrip("/")
    parsed = urlsplit(base_url)
    try:
        # Force lazy port parsing and reject explicit port zero before work is
        # admitted; both would otherwise fail only in the HTTP client.
        _validated_url_port(parsed)
    except ValueError as exc:
        raise ValueError("AI-OpenRouter gateway configuration is incomplete or invalid") from exc
    if not settings.AI_OPENROUTER_API_KEY.strip() or not (parsed.scheme == "https" and parsed.hostname and not parsed.username and not parsed.password and not parsed.query and not parsed.fragment):
        raise ValueError("AI-OpenRouter gateway configuration is incomplete or invalid")
    return GatewayConfig(base_url, settings.AI_OPENROUTER_API_KEY.strip())

def external_gateway_hosts() -> tuple[str, ...]:
    """Validated gateway hostname(s) that the egress guard must treat as a provider.

    The gateway is a service-owned inference endpoint, so it needs the same
    provider exemption as the static provider hosts; otherwise profiled research
    would apply a public-domain allowlist and refuse the configured gateway.
    Only the validated hostname is returned, never the credential.
    """
    try:
        gateway = external_openai_gateway_config()
    except ValueError:
        return ()
    if not gateway:
        return ()
    hostname = urlsplit(gateway.base_url).hostname
    return (hostname.lower().rstrip("."),) if hostname else ()


def local_model_endpoint() -> tuple[str, int] | None:
    """Host/port of the configured local model endpoint, or None if not local.

    A provider name alone does not establish locality: ``OLLAMA_BASE_URL`` can be
    pointed at a public host. Only loopback, RFC 1918, or IPv6 ULA endpoints are
    accepted as local, so a "local" model selection can never become an
    unmetered external egress path or bypass the shared gateway.
    """
    parsed = urlsplit(settings.OLLAMA_BASE_URL.strip())
    if (
        parsed.scheme not in ("http", "https")
        or not parsed.hostname
        or parsed.path not in ("", "/")
    ):
        return None
    host = parsed.hostname.lower().rstrip(".")
    try:
        address = ipaddress.ip_address(host)
    except ValueError:
        if host != "localhost":
            return None
        address = ipaddress.ip_address("127.0.0.1")
    if not any(address in network for network in _LOCAL_MODEL_NETWORKS):
        return None
    try:
        port = _validated_url_port(
            parsed, 443 if parsed.scheme == "https" else 80
        )
    except ValueError:
        return None
    return host, port


def brain_memory_client():
    """Return the optional Brain client only for a complete, explicit config."""
    if not settings.BRAIN_MEMORY_ENABLED:
        return None
    values = {
        "BRAIN_MEMORY_URL": settings.BRAIN_MEMORY_URL.strip(),
        "BRAIN_MEMORY_KEY_ID": settings.BRAIN_MEMORY_KEY_ID.strip(),
        "BRAIN_MEMORY_SECRET": settings.BRAIN_MEMORY_SECRET.strip(),
    }
    missing = [name for name, value in values.items() if not value]
    if missing:
        _logger.warning("Brain Memory disabled because its credential group is incomplete: %s", ", ".join(missing))
        return None
    try:
        from app.brain_memory import BrainMemoryClient
        return BrainMemoryClient(values["BRAIN_MEMORY_URL"], values["BRAIN_MEMORY_KEY_ID"], values["BRAIN_MEMORY_SECRET"])
    except ValueError:
        _logger.warning("Brain Memory disabled because its URL is invalid", exc_info=True)
        return None
